CREATE DATABASE BOARD_EX;

USE BOARD_EX;

CREATE TABLE BOARD(
	BOARD_ID 	BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER 		VARCHAR(50),
    EMAIL 		VARCHAR(50),
    SUBJECT 	VARCHAR(100),
    PASSWORD 	VARCHAR(20),
    ENROLL_DT 	TIMESTAMP,
    READ_CNT    BIGINT,
   	CONTENT     VARCHAR(2000)
);
